
using System.Collections.Generic;

public class SupermodelInputs
{
    /*
    public static Dictionary<KeyCode, string> keyCodesToSupermodelInputs = new Dictionary<KeyCode, string>()
    {
        { KeyCode.JoystickButton0, "JOY1_BUTTON1" },
        { KeyCode.JoystickButton1, "JOY1_BUTTON2" },
        { KeyCode.JoystickButton2, "JOY1_BUTTON3" },
        { KeyCode.JoystickButton3, "JOY1_BUTTON4" },
        { KeyCode.JoystickButton4, "JOY1_BUTTON5" },
        { KeyCode.JoystickButton5, "JOY1_BUTTON6" },
        { KeyCode.JoystickButton6, "JOY1_BUTTON7" },
        { KeyCode.JoystickButton7, "JOY1_BUTTON8" },
        { KeyCode.JoystickButton8, "JOY1_BUTTON9" },
        { KeyCode.JoystickButton9, "JOY1_BUTTON10" },
        { KeyCode.JoystickButton10, "JOY1_BUTTON11" },
        { KeyCode.JoystickButton11, "JOY1_BUTTON12" },
        { KeyCode.JoystickButton12, "JOY1_BUTTON13" },
        { KeyCode.JoystickButton13, "JOY1_BUTTON14" },
        { KeyCode.JoystickButton14, "JOY1_BUTTON15" },
        { KeyCode.JoystickButton15, "JOY1_BUTTON16" },
        { KeyCode.JoystickButton16, "JOY1_BUTTON17" },
        { KeyCode.JoystickButton17, "JOY1_BUTTON18" },
        { KeyCode.JoystickButton18, "JOY1_BUTTON19" },
        { KeyCode.JoystickButton19, "JOY1_BUTTON20" },
        { KeyCode.Joystick1Button0, "JOY1_BUTTON1" },
        { KeyCode.Joystick1Button1, "JOY1_BUTTON2" },
        { KeyCode.Joystick1Button2, "JOY1_BUTTON3" },
        { KeyCode.Joystick1Button3, "JOY1_BUTTON4" },
        { KeyCode.Joystick1Button4, "JOY1_BUTTON5" },
        { KeyCode.Joystick1Button5, "JOY1_BUTTON6" },
        { KeyCode.Joystick1Button6, "JOY1_BUTTON7" },
        { KeyCode.Joystick1Button7, "JOY1_BUTTON8" },
        { KeyCode.Joystick1Button8, "JOY1_BUTTON9" },
        { KeyCode.Joystick1Button9, "JOY1_BUTTON10" },
        { KeyCode.Joystick1Button10, "JOY1_BUTTON11" },
        { KeyCode.Joystick1Button11, "JOY1_BUTTON12" },
        { KeyCode.Joystick1Button12, "JOY1_BUTTON13" },
        { KeyCode.Joystick1Button13, "JOY1_BUTTON14" },
        { KeyCode.Joystick1Button14, "JOY1_BUTTON15" },
        { KeyCode.Joystick1Button15, "JOY1_BUTTON16" },
        { KeyCode.Joystick1Button16, "JOY1_BUTTON17" },
        { KeyCode.Joystick1Button17, "JOY1_BUTTON18" },
        { KeyCode.Joystick1Button18, "JOY1_BUTTON19" },
        { KeyCode.Joystick1Button19, "JOY1_BUTTON20" },
        { KeyCode.Joystick2Button0, "JOY2_BUTTON1" },
        { KeyCode.Joystick2Button1, "JOY2_BUTTON2" },
        { KeyCode.Joystick2Button2, "JOY2_BUTTON3" },
        { KeyCode.Joystick2Button3, "JOY2_BUTTON4" },
        { KeyCode.Joystick2Button4, "JOY2_BUTTON5" },
        { KeyCode.Joystick2Button5, "JOY2_BUTTON6" },
        { KeyCode.Joystick2Button6, "JOY2_BUTTON7" },
        { KeyCode.Joystick2Button7, "JOY2_BUTTON8" },
        { KeyCode.Joystick2Button8, "JOY2_BUTTON9" },
        { KeyCode.Joystick2Button9, "JOY2_BUTTON10" },
        { KeyCode.Joystick2Button10, "JOY2_BUTTON11" },
        { KeyCode.Joystick2Button11, "JOY2_BUTTON12" },
        { KeyCode.Joystick2Button12, "JOY2_BUTTON13" },
        { KeyCode.Joystick2Button13, "JOY2_BUTTON14" },
        { KeyCode.Joystick2Button14, "JOY2_BUTTON15" },
        { KeyCode.Joystick2Button15, "JOY2_BUTTON16" },
        { KeyCode.Joystick2Button16, "JOY2_BUTTON17" },
        { KeyCode.Joystick2Button17, "JOY2_BUTTON18" },
        { KeyCode.Joystick2Button18, "JOY2_BUTTON19" },
        { KeyCode.Joystick2Button19, "JOY2_BUTTON20" },
        { KeyCode.Joystick3Button0, "JOY3_BUTTON1" },
        { KeyCode.Joystick3Button1, "JOY3_BUTTON2" },
        { KeyCode.Joystick3Button2, "JOY3_BUTTON3" },
        { KeyCode.Joystick3Button3, "JOY3_BUTTON4" },
        { KeyCode.Joystick3Button4, "JOY3_BUTTON5" },
        { KeyCode.Joystick3Button5, "JOY3_BUTTON6" },
        { KeyCode.Joystick3Button6, "JOY3_BUTTON7" },
        { KeyCode.Joystick3Button7, "JOY3_BUTTON8" },
        { KeyCode.Joystick3Button8, "JOY3_BUTTON9" },
        { KeyCode.Joystick3Button9, "JOY3_BUTTON10" },
        { KeyCode.Joystick3Button10, "JOY3_BUTTON11" },
        { KeyCode.Joystick3Button11, "JOY3_BUTTON12" },
        { KeyCode.Joystick3Button12, "JOY3_BUTTON13" },
        { KeyCode.Joystick3Button13, "JOY3_BUTTON14" },
        { KeyCode.Joystick3Button14, "JOY3_BUTTON15" },
        { KeyCode.Joystick3Button15, "JOY3_BUTTON16" },
        { KeyCode.Joystick3Button16, "JOY3_BUTTON17" },
        { KeyCode.Joystick3Button17, "JOY3_BUTTON18" },
        { KeyCode.Joystick3Button18, "JOY3_BUTTON19" },
        { KeyCode.Joystick3Button19, "JOY3_BUTTON20" },
        { KeyCode.Joystick4Button0, "JOY4_BUTTON1" },
        { KeyCode.Joystick4Button1, "JOY4_BUTTON2" },
        { KeyCode.Joystick4Button2, "JOY4_BUTTON3" },
        { KeyCode.Joystick4Button3, "JOY4_BUTTON4" },
        { KeyCode.Joystick4Button4, "JOY4_BUTTON5" },
        { KeyCode.Joystick4Button5, "JOY4_BUTTON6" },
        { KeyCode.Joystick4Button6, "JOY4_BUTTON7" },
        { KeyCode.Joystick4Button7, "JOY4_BUTTON8" },
        { KeyCode.Joystick4Button8, "JOY4_BUTTON9" },
        { KeyCode.Joystick4Button9, "JOY4_BUTTON10" },
        { KeyCode.Joystick4Button10, "JOY4_BUTTON11" },
        { KeyCode.Joystick4Button11, "JOY4_BUTTON12" },
        { KeyCode.Joystick4Button12, "JOY4_BUTTON13" },
        { KeyCode.Joystick4Button13, "JOY4_BUTTON14" },
        { KeyCode.Joystick4Button14, "JOY4_BUTTON15" },
        { KeyCode.Joystick4Button15, "JOY4_BUTTON16" },
        { KeyCode.Joystick4Button16, "JOY4_BUTTON17" },
        { KeyCode.Joystick4Button17, "JOY4_BUTTON18" },
        { KeyCode.Joystick4Button18, "JOY4_BUTTON19" },
        { KeyCode.Joystick4Button19, "JOY4_BUTTON20" },
    };

    public static Dictionary<string, string> axisFullToSupermodelInputs = new Dictionary<string, string>()
    {
        { "Joy1Axis1", "JOY1_XAXIS" },
        { "Joy1Axis2", "JOY1_YAXIS" },
        { "Joy1Axis3", "JOY1_ZAXIS" },
        { "Joy1Axis4", "JOY1_RXAXIS" },
    };

    public static Dictionary<string, string> axisSignedToSupermodelInputs = new Dictionary<string, string>()
    {
        { "Joy1Axis1", "JOY1_XAXIS_POS" },
        { "-Joy1Axis1", "JOY1_XAXIS_NEG" },
        { "Joy1Axis2", "JOY1_YAXIS_POS" },
        { "-Joy1Axis2", "JOY1_YAXIS_NEG" },
        { "Joy1Axis3", "JOY1_ZAXIS_POS" },
        { "-Joy1Axis3", "JOY1_ZAXIS_NEG" },
        { "Joy1Axis4", "JOY1_RXAXIS_POS" },
        { "-Joy1Axis4", "JOY1_RXAXIS_NEG" },

        { "Joy1Axis6", "JOY1_RIGHT" },
        { "-Joy1Axis6", "JOY1_LEFT" },
        { "Joy1Axis7", "JOY1_UP" },
        { "-Joy1Axis7", "JOY1_DOWN" },
    };
    
    */

    public enum SupermodelInputAxes
    {
        InputJoy1X,
        InputJoy1Y,
        InputJoy1RX,
        InputJoy1RY,
        InputJoy1Z,
        InputJoy2X,
        InputJoy2Y,
        InputJoy2RX,
        InputJoy2RY,
        InputJoy2Z,
        InputJoy3X,
        InputJoy3Y,
        InputJoy3RX,
        InputJoy3RY,
        InputJoy3Z,
        InputJoy4X,
        InputJoy4Y,
        InputJoy4RX,
        InputJoy4RY,
        InputJoy4Z,
    }           

    public enum SupermodelInputSegaRally2
    {
        InputStart1,
        InputCoin1,
        InputSteeringLeft,
        InputSteeringRight,
        InputSteering,
        InputAccelerator,
        InputBrake,
        InputGearShiftUp,
        InputGearShiftDown,
        InputGearShift1,
        InputGearShift2,
        InputGearShift3,
        InputGearShift4,
        InputGearShiftN,
        InputViewChange,
        InputHandBrake
    }

    public enum SupermodelInputType
    {
        InputStart1,
        InputStart2,
        InputCoin1,
        InputCoin2,
        InputServiceA,
        InputServiceB,
        InputTestA,
        InputTestB,
        InputJoyUp,
        InputJoyDown,
        InputJoyLeft,
        InputJoyRight,
        InputJoyUp2,
        InputJoyDown2,
        InputJoyLeft2,
        InputJoyRight2,
        InputPunch,
        InputKick,
        InputGuard,
        InputEscape,
        InputPunch2,
        InputKick2,
        InputGuard2,
        InputEscape2,
        InputShift,
        InputBeat,
        InputCharge,
        InputJump,
        InputShortPass,
        InputLongPass,
        InputShoot,
        InputShortPass2,
        InputLongPass2,
        InputShoot2,
        InputSteeringLeft,
        InputSteeringRight,
        InputSteering,
        InputAccelerator,
        InputBrake,
        InputGearShiftUp,
        InputGearShiftDown,
        InputGearShift1,
        InputGearShift2,
        InputGearShift3,
        InputGearShift4,
        InputGearShiftN,
        InputVR1,
        InputVR2,
        InputVR3,
        InputVR4,
        InputViewChange,
        InputHandBrake,
        InputRearBrake,
        InputMusicSelect,
        InputTwinJoyTurnLeft,
        InputTwinJoyTurnRight,
        InputTwinJoyForward,
        InputTwinJoyReverse,
        InputTwinJoyStrafeLeft,
        InputTwinJoyStrafeRight,
        InputTwinJoyJump,
        InputTwinJoyCrouch,
        InputTwinJoyLeft1,
        InputTwinJoyLeft2,
        InputTwinJoyRight1,
        InputTwinJoyRight2,
        InputTwinJoyUp1,
        InputTwinJoyUp2,
        InputTwinJoyDown1,
        InputTwinJoyDown2,
        InputTwinJoyShot1,
        InputTwinJoyShot2,
        InputTwinJoyTurbo1,
        InputTwinJoyTurbo2,
        InputAnalogJoyLeft,
        InputAnalogJoyRight,
        InputAnalogJoyUp,
        InputAnalogJoyDown,
        InputAnalogJoyX,
        InputAnalogJoyY,
        InputAnalogJoyTrigger,
        InputAnalogJoyEvent,
        InputAnalogJoyTrigger2,
        InputAnalogJoyEvent2,
        InputGunLeft,
        InputGunRight,
        InputGunUp,
        InputGunDown,
        InputGunX,
        InputGunY,
        InputTrigger,
        InputOffscreen,
        InputAutoTrigger,
        InputGunLeft2,
        InputGunRight2,
        InputGunUp2,
        InputGunDown2,
        InputGunX2,
        InputGunY2,
        InputTrigger2,
        InputOffscreen2,
        InputAutoTrigger2,
        InputAnalogGunLeft,
        InputAnalogGunRight,
        InputAnalogGunUp,
        InputAnalogGunDown,
        InputAnalogGunX,
        InputAnalogGunY,
        InputAnalogTriggerLeft,
        InputAnalogTriggerRight,
        InputAnalogGunLeft2,
        InputAnalogGunRight2,
        InputAnalogGunUp2,
        InputAnalogGunDown2,
        InputAnalogGunX2,
        InputAnalogGunY2,
        InputAnalogTriggerLeft2,
        InputAnalogTriggerRight2,
        InputSkiLeft,
        InputSkiRight,
        InputSkiUp,
        InputSkiDown,
        InputSkiX,
        InputSkiY,
        InputSkiPollLeft,
        InputSkiPollRight,
        InputSkiSelect1,
        InputSkiSelect2,
        InputSkiSelect3,
        InputMagicalLeverUp1,
        InputMagicalLeverDown1,
        InputMagicalLeverUp2,
        InputMagicalLeverDown2,
        InputMagicalLever1,
        InputMagicalLever2,
        InputMagicalPedal1,
        InputMagicalPedal2,
        InputFishingRodLeft,
        InputFishingRodRight,
        InputFishingRodUp,
        InputFishingRodDown,
        InputFishingStickLeft,
        InputFishingStickRight,
        InputFishingStickUp,
        InputFishingStickDown,
        InputFishingRodX,
        InputFishingRodY,
        InputFishingStickX,
        InputFishingStickY,
        InputFishingReel,
        InputFishingCast,
        InputFishingSelect
    }
}